<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFrameworks>net10.0;net11.0</TargetFrameworks>
        <Features Condition="'$(TargetFramework)' == 'net11.0'">runtime-async=on</Features>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <LangVersion>preview</LangVersion>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <TargetsForTfmSpecificBuildOutput>$(TargetsForTfmSpecificBuildOutput);IncludeProjectReferenceDlls</TargetsForTfmSpecificBuildOutput>
        <TargetsForTfmSpecificContentInPackage>$(TargetsForTfmSpecificContentInPackage);IncludeReferenceAssemblies</TargetsForTfmSpecificContentInPackage>
        <NoWarn>$(NoWarn);NU5131;DRAGHI001;SLONPG001;SLONPOOL001</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Slon.Benchmark"/>
        <InternalsVisibleTo Include="Slon.NativeAotSample"/>
        <InternalsVisibleTo Include="Slon.Tests"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.0"/>
        <PackageReference Include="Microsoft.CodeAnalysis.PublicApiAnalyzers" Version="3.3.4" PrivateAssets="all" />
        <ProjectReference Include="../../Draghi/Draghi.Pipelining/Draghi.Pipelining.csproj"/>
    </ItemGroup>

    <Target Name="IncludeProjectReferenceDlls" DependsOnTargets="BuildOnlySettings;ResolveReferences">
        <ItemGroup>
            <BuildOutputInPackage Include="@(ReferenceCopyLocalPaths->WithMetadataValue('ReferenceSourceTarget', 'ProjectReference')->WithMetadataValue('PrivateAssets', 'All'))"
                                  TargetPath="%(ReferenceCopyLocalPaths.DestinationSubDirectory)"/>
        </ItemGroup>
    </Target>

    <!-- Add a ref folder to the package which only exposes the library so that the referenced class library doesn't get exposed. -->
    <Target Name="IncludeReferenceAssemblies">
        <ItemGroup>
            <TfmSpecificPackageFile Include="$(TargetPath)" PackagePath="ref/$(TargetFramework)"/>
        </ItemGroup>
    </Target>
</Project>
